# Generated by Django 5.1.1 on 2024-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_locationdetails_itinerary_images_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
