# Generated by Django 5.1.1 on 2024-09-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_id_alter_images_id_alter_itinerary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='original',
            field=models.URLField(blank=True, null=True),
        ),
    ]
