# Generated by Django 5.1.1 on 2024-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_images_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='large',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='small',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='postalcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
