# Generated by Django 5.1.1 on 2024-09-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_images_large_alter_images_medium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='itinerary_id',
            new_name='itinerary',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='user_id',
            new_name='user',
        ),
    ]
