# Generated by Django 5.1.1 on 2024-09-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_itinerary_id_activity_itinerary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locationdetails'),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='address_string',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='ranking',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='street1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='street2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(null=True)),
                ('small', models.URLField(null=True)),
                ('medium', models.URLField(null=True)),
                ('large', models.URLField(null=True)),
                ('original', models.URLField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locationdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
