# Generated by Django 5.1.1 on 2024-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_activity_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='address_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='postalcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='ranking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='street1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetails',
            name='street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
