# Generated by Django 5.1.1 on 2024-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_locationdetails_address_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
