# Generated by Django 5.1.1 on 2024-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_itinerary_destination_itinerary_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
